version: "3"
services:
  proxy:
    image: ghcr.io/ddadaal/vpn-as-http-proxy
    container_name: vpnproxy
    environment: 
      - PORT=8888
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - ${PORT}:8888
    # https://stackoverflow.com/questions/30547484/calling-openconnect-vpn-client-in-docker-container-shows-tunsetiff-failed-opera
    cap_add: 
      - NET_ADMIN
    volumes:
      - ${HOME}/.ssh:/root/.ssh
    command: bash -c '
        chmod 400 /root/.ssh/id_rsa &&
        tinyproxy &&
        ${CMD}
      '